name: Build and Test

on:
  pull_request:
  push:
    branches:
      - test
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Install dotnet 3.1'
        uses: actions/setup-dotnet@v1.0.0
        with:
          version: 3.1.100
 
      - name: 'Build'
        working-directory: 'src'
        run: dotnet build
           
